tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "bash-completion"
brew "coreutils"
brew "git"
brew "gnupg"
brew "iperf3"
brew "mas"
brew "ncdu"
brew "pinentry-mac"
brew "rename"
brew "rsync"
brew "tree"
brew "trash"
brew "ykman"
cask "appcleaner"
cask "atom"
cask "brave-browser"
cask "daisydisk"
cask "docker"
cask "keka"
cask "plexamp"
cask "transmission"
cask "virtualbox"
cask "vagrant"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
mas "Adblock Plus", id: 1432731683
mas "Numbers", id: 409203825
mas "Trello", id: 1278508951
mas "WireGuard", id: 1451685025
